// Generated by CoffeeScript 1.7.1
(function() {
  var coffee, concat, gulp, jade, less, paths, src_files, tap, watch;

  paths = require('path');

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  less = require('gulp-less');

  watch = require('gulp-watch');

  tap = require('gulp-tap');

  jade = require('gulp-jade');

  concat = require('gulp-concat');

  src_files = {
    modules_less: 'modules/**/views/assets/stylesheets/*.less',
    modules_coffee: ['modules/**/configs/*.coffee', 'modules/**/controllers/*.coffee', 'modules/**/directives/*.coffee', 'modules/**/services/*.coffee', 'modules/**/app.coffee'],
    modules_jade: ['modules/**/views/*.jade']
  };

  gulp.task('less', function() {
    return gulp.src(src_files.modules_less).pipe(watch({
      name: 'less',
      emit: 'all',
      glob: src_files.modules_less
    }, function(files) {
      return files.pipe(less()).pipe(concat('all.css')).pipe(gulp.dest('./dist'));
    }));
  });

  gulp.task('coffee', function() {
    return gulp.src(src_files.modules_coffee).pipe(watch({
      name: 'coffee',
      emit: 'all',
      glob: src_files.modules_coffee
    }, function(files) {
      return files.pipe(coffee()).pipe(concat('all.js')).pipe(gulp.dest('./dist'));
    }));
  });

  gulp.task('jade', function() {
    return gulp.src(src_files.modules_jade).pipe(watch({
      name: 'jade',
      emit: 'one',
      glob: src_files.modules_jade
    }, function(files) {
      return files.pipe(jade()).pipe(gulp.dest('./dist'));
    }));
  });

  gulp.task('watch-all', function() {
    gulp.src(src_files.modules_jade).pipe(watch({
      name: 'jade',
      emit: 'one',
      glob: src_files.modules_jade
    }, function(files) {
      return files.pipe(jade()).pipe(gulp.dest('./dist'));
    }));
    gulp.src(src_files.modules_coffee).pipe(watch({
      name: 'coffee',
      emit: 'all',
      glob: src_files.modules_coffee
    }, function(files) {
      return files.pipe(coffee()).pipe(concat('all.js')).pipe(gulp.dest('./dist'));
    }));
    return gulp.src(src_files.modules_less).pipe(watch({
      name: 'less',
      emit: 'all',
      glob: src_files.modules_less
    }, function(files) {
      return files.pipe(less()).pipe(concat('all.css')).pipe(gulp.dest('./dist'));
    }));
  });

}).call(this);
